### ISSUE TITLE
Singing Solo

### ISSUE THREAD

**Issue by xNocki** [Ivaar/Windower-addons#1]
There is currently a bug where if you were to run this program without any party members, it will just repeat your initial 2 songs without considering any extra songs.

**Comment by Ivaar** [comment]
This is now resolved, I removed the settings and commands for AoE watch list in favor of an ignore list. The addon will not wait for Ignored party members to be inside AoE range (This will later ignore party members when repositioning prior to casting AoE songs.). Additionally, Ignoring yourself should prevent casting AoE songs if party members are not in the same zone.
