### ISSUE TITLE
Add a way to monitor players vs blacklisting them

### ISSUE THREAD

**Issue by Noctis32** [Ivaar/Windower-addons#11]
Hi there,

First off would like to thank you for making this amazing BRD bot addon. However, I have 1 suggestion. Instead, of players you have to put on ignore so the BRD addon sings if they are not in range, would it not be better if you made a white list instead? I mean, of players that have to be in range for the BRD bot to sing? Because at some point my ignore list is getting huge containing over 30+ players. But if I just add my own char and maybe 2-4 players I play a lot with the list would get much smaller.

Thank you for your work :)

**Comment by Ivaar** [comment]
A list of monitored players sounds like a good idea. As I've mentioned before I put this together from examples I found when first learning Lua for windower API. I want to clean up the code and reduce some api calls and possibly integrate the logic into a full party bot. Unfortunately I don't want to make any major changes until I see windower 5 API. I'm thinking of changing the "active" text box into a GUI object where you would be able to check a box next to the party members you want monitored. On addon reload, the players or party slots would remain checked.

**Comment by Ivaar** [comment]
Implemented
