### ISSUE TITLE
TradeNPC "No target or too far away"

### ISSUE THREAD

**Issue by aboYoda** [Ivaar/Windower-addons#12]
Trying to trade Infinity Core + Chip to Strange Apparatus and it's saying "no target or too far away", manually trading I am within the proper distance to trade.

**Comment by Ivaar** [comment]
You will need to manually target the Strange Apparatus before typing your command. Make sure you have spelled the items correctly and used the proper command format, you may use auto-translate when in doubt.  e.g. `//tradenpc 1 infinity core 1 red chip`

**Comment by aboYoda** [comment]
Hi Ivaar, I am 2 yalms away and tried the exact command you said, and it still gives the error message in console. When i manually trade I am close enough, but the plugin throws and error like i'm too far away.

https://imgur.com/ngGEQRW using plugin
https://imgur.com/osTHgM0 manual trading

**Comment by Ivaar** [comment]
Can you load [this](https://gist.github.com/Ivaar/9abb704eec00004cc451ee63e3d5b659) trade manually and tell me what it says for spawn_type

**Comment by Ivaar** [comment]
Fixed to properly check NPC spawn_type flag
