### ISSUE TITLE
Issue with extra song not equipping instrument

### ISSUE THREAD

**Issue by Damosthenes** [Ivaar/Windower-addons#14]
I read through the other issues and this might just be me setting things up wrong. I have Terpander (1 extra song) so with clarion call it should get me 4 songs. 
![image](https://user-images.githubusercontent.com/9699790/44919115-a982cd00-ad0a-11e8-92eb-cf325c72adc8.png)
This is how I set it up, 3 songs with 4th set to clarion, but like this: 
1) it will only use Terpander if it's in my inventory and seems to ignore wardrobe, 
2) It won't use clarion call
If I make it 4 songs (4th being the same as clarion) then it still won't use clarion call and will just endlessly cycle the 4 songs in the 3 slots.

**Comment by Ivaar** [comment]
You should be using gearswap for changing instruments for dummy songs, this only reads your currently equipped gear to calculate song durations, which should be changed to read the buff packets instead.

**Comment by Damosthenes** [comment]
Ah, so I need to trigger the dummy song on my gs? I thought this add-on would trigger it via my gs. 

Along this line, if I put all 4 songs up then turn on singer it seems to do just fine for a bit but after 2-3 cycles of songs it will drop the 4th song.

**Comment by Ivaar** [comment]
This could be an error in the gear duration calculation or not everyone in the party was in range for recast?
I think that's why the ignore list is there to make sure it doesn't wait on pullers and the like.

**Comment by Ivaar** [comment]
It wants to make sure everyone is in range before buffing, I don't remember if it makes sure  everyone is in range to recast... It should just recast.
