### ISSUE TITLE
Song Looping

### ISSUE THREAD

**Issue by lopperlooping** [Ivaar/Windower-addons#16]
It keeps recasting a song once its off delay, so with my current gear it can only sing 3 songs, then it loops back to the start.. Recast is set to 25-30(it will recast even tho time remaining is 10+ minutes). The buff (haste/refresh) loops properly on recast. I think maybe related ot the error i recieved trying to do "//sing timers off" it says... "Singer: Lua runtime error: singer/singer.lua306: attempt to call global 'reset_timers' (a nil value)
Also not sure when its supposed to sing a dummy song, but it ignores it completely.
the WS:[>20%}{<99%] thing is unexplained in readme.

**Comment by Ivaar** [comment]
Sounds like you have new +song gear that hasn't been added to singer. The error message is unrelated, function was changed to song_timers.reset and that's the only instance that still exists.

If you have a 3 song instrument it should sing whatever you have set for dummy1 before applying the third song. If you are not full-timing it you will need gearswap setup to swap to your 3 song instrument when dummy song is used.

The weapon skill stuff is for maintaining mythic AM3 and does nothing if you aren't equipped with carnwenhan. Its just min/max target hp for weapon skill usage.

**Comment by lopperlooping** [comment]
its not singing dummy1, and i tried on a mule tha tonly has terp (nmo other gear) same issue. 
also i do have carn, will it ws? because i dont want it to

**Comment by lopperlooping** [comment]
[https://imgur.com/a/TQy6z9j](url)

This is my gear singing right now, gearswap disabled, and singer settings. It is just spamming minuet V until one of the other songs comes low on cooldown. It is not singing minne (the dummy song) as u cans ee these are pretty much right out of the box settings, please advise.

**Comment by Ivaar** [comment]
Need to add support for wardrobe 2-4, if your 3 song harp is in one of those bags it wont detect it. All other gear calculations are done on current equipment so they can be in any bag.

**Comment by lopperlooping** [comment]
Ah interesting, that may be it then because i only use 3 and 4 for weapons and ranged slots

**Comment by lopperlooping** [comment]
Same settings, harp equipped form inventory, its just spamming songs still, as soon as they are off cooldown.

**Comment by Ivaar** [comment]
If you want I can try to help you on discord Ivaar#6857, It sounds like you may have new equipment that needs to be adjusted for, also try using dummy songs that you know aren't going to have a greatly enhanced duration from gear. Is it at least using the dummy song now?

**Comment by lopperlooping** [comment]
No new gear completely naked, only dummy song instrument equipped. 
Not singing dummy song no. Not even singing the right song tbh, minuet 1, its singing both 5 and 4. 

I will try new version now.

**Comment by lopperlooping** [comment]
okay, tested naked with daruda on, daurda from inventory. Works perfectly, sings dummy songs and then refreshes songs correctly.. Testing now with daruda in mog wardrobe 4.

**Comment by lopperlooping** [comment]
Okay it works perfect, I dont know what you did but this is wonderful work. 
Also this app in general is really well executed it has everything a brd needs. Thank you very much.
