### ISSUE TITLE
[Singer] Multiple Harps maxsongs

### ISSUE THREAD

**Issue by toioiz** [Ivaar/Windower-addons#17]
If you have a 99 Dauradabla and a Blurred Harp +1 - it appears to set maxsongs to 3 instead of 4 - there are reasons to have both - larger number should win.

**Comment by Ivaar** [comment]
For the time being you may place your Daurdabla in a bag with a higher priority.
e.g. Daurdabla in wardrobe 1 and Blurred Harp in wardrobe2.
This is the order bags are checked: inventory>wardrobe>wardrobe2>wardrobe3>wardrobe4.

**Comment by Ivaar** [comment]
Singer now checks for the highest additional song harp
