### ISSUE TITLE
Recasts all song buffs after sleeping mobs 

### ISSUE THREAD

**Issue by jsmcewen** [Ivaar/Windower-addons#18]
When in a CP party pulling with brd after every pull/sleep it recasts songs

**Comment by Ivaar** [comment]
Are the song buffs hitting all other party members? Have you tried ignoring party members who may not always be in range for songs? I will attempt to replicate, however I feel I'm going to need more info.

**Comment by Ivaar** [comment]
Do you know if this was this an issue prior to recent updates of Singer?

**Comment by jsmcewen** [comment]
I will test it out tonight
