### ISSUE TITLE
Randomly won't work

### ISSUE THREAD

**Issue by anthem127** [Ivaar/Windower-addons#19]
I'm not sure if its by zone, because the group is moving or stationary.  Today before I updated to the latest release it outright refuses to work and some with today after I updated.  I cleaned out all the old files and started clean, restarted the BRD's Pol window and even went as far as to shut down all other addons.  I'm in Yahse Hunting Grounds, refuses to sing anything.  Doesn't matter if its clean or not.  Yesterday I tried to use on SKY and nada.  Seems to behave when I'm CPing and not moving at all. I tested in Yahse Hunting Grounds not moving and nada.

Let me know if I can provide anything to assist.  Its worked lovely for CPing for a long time just acts up when I'm either moving a lot or in the odd zone.

**Comment by Ivaar** [comment]
I suspect this is the same issue as #18, party members need to be added to ignore list if they are not in range. I've been meaning to make a toggle for that and/or bring back the AoE watchlist.

**Comment by anthem127** [comment]
This would make sense.  On all occasions maybe a PL was sitting out of
range to not gt hit with AOE and also explain why not working while moving
in DDyna.
