### ISSUE TITLE
Instruments are not equiping.

### ISSUE THREAD

**Issue by hectordc5** [Ivaar/Windower-addons#2]
Everything works as it's intended. The only issue is instruments like Daurdabla(99) and Gjallarhorn are not getting equipped when singing dummy songs and normal songs.

**Comment by Ivaar** [comment]
This was intended to be used with gearswap. If you do not have one for bard that equips daurdabla for dummy songs then I recommend this: [http://pastebin.com/TuFmqY1F](http://pastebin.com/TuFmqY1F )

This addon doesn't recognize any gear introduced over the past year and it will only look for your dummy instrument in main inventory/wardrobe 1. I can add new wardrobes this weekend but I do not know what has been added aside from new R/M/E trials and empyrean 119?

**Comment by bluethunder1080** [comment]
Just checking, was this already updated with that information?
and does it work with the JSE oboro harp, and all versions of the daurdabla and Ghorn?

thanks :)

**Comment by Ivaar** [comment]
It was. Everything should be working.
