### ISSUE TITLE
Settings file?

### ISSUE THREAD

**Issue by tehfailsafe** [Ivaar/Windower-addons#26]
For singer, autocor, autogeo, is there a settings.xml that can be used or something instead of reverting to defaults every game load?

**Comment by Ivaar** [comment]
The settings.xml is generated automatically when loading the addon. You can edit that directly or use the addons save command. Before editing settings.xml you should unload the addon to avoid your changes being overwritten on unload/reload.

**Comment by tehfailsafe** [comment]
I see, awesome, I didn't seen any commands for save or any xml files anywhere and every time I log in singer resets to the default songs, buffs, etc
