### ISSUE TITLE
Clarion not trigger?

### ISSUE THREAD

**Issue by jmhgit** [Ivaar/Windower-addons#28]
My gear is a bit lacking, as I only have Terpander for extra songs. Everything seems to work fine with the exception of Clarion Call being used.

Am I doing something wrong or is it broken?

![image](https://user-images.githubusercontent.com/60338633/77840031-638d2580-7148-11ea-848b-f55ed47ca13d.png)

Seems like it's this issue, except this was closed with no solution listed
https://github.com/Ivaar/Windower-addons/issues/14

**Comment by Ivaar** [comment]
Singer does not use clarion call, this is by design. Per your settings, an extra minuet will be used if clarion buff is detected or an extra song is present. I might be willing to tie ability usage to a non default setting.

**Comment by jmhgit** [comment]
oh thanks for your quick response, makes sense. I was thinking it would trigger clarion.
