### ISSUE TITLE
Pia songs?

### ISSUE THREAD

**Issue by ukkoclap** [Ivaar/Windower-addons#3]
Sorry I think I'm retarded but I can't figure out how to do Pia Ballads on another player

I tried

//sing ballad x Charactername 
//sing ballad on Charactername
//sing ballad n Charactername

//sing "Mage's Ballad II" x Charactername 
//sing "Mage's Ballad II" on Charactername
//sing "Mage's Ballad II" n Charactername

None of those seem to work :(

Is there also a way to make it cast Elegy?

**Comment by Ivaar** [comment]
//sing ballad 2 player_name (will pianissimo double ballads on player_name) 
//sing ballad off player_name (will stop singing ballads for player_name)

[n] represents the number of songs types you want to use. Singer will prioritize higher tier songs, so if [n] is set to 1 "Mage's Ballad II" will be used, while if set to 2 both ballads will be used.

**Comment by Ivaar** [comment]
Additionally, you may need to turn pianissimo on.

//sing pianissimo on

**Comment by ukkoclap** [comment]
Thanks for the fast reply. One more question i seem to be able to sing in a 3-man party but if there's 4 or more party members it refuses to sing. Is there an option that it allows to sing in a full party?

**Comment by Ivaar** [comment]
Try deleting the settings.xml file located in the singer data folder and starting fresh. I will try to reproduce the issues, if you can provide any more info it may help. I haven't played in several years so you'll have to bare with me.

**Comment by Ivaar** [comment]
I see both issues and I will find out what has changed, I should have a fix soon. I haven't played in several years so you'll have to bare with me.

**Comment by ukkoclap** [comment]
Ok thank you for looking into it. Looking forward to your update :)

**Comment by Ivaar** [comment]
Ignore should be working now. Make sure to delete your settings.xml file located inside the addons data folder, as I was not able to reproduce any error messages, this might also solve your pianissimo spam. For me the problem was I had not setup the proper dummy songs within the addon. Are you using a 3+ song bard with gearswap to change instruments? If so are the 3+ songs being applied to pianissimo targets?

**Comment by ukkoclap** [comment]
Hi. Thanks for updating. Ignore does work now but when I turn on Pianissimo i get this error. And it spams it.

https://i.imgur.com/YFtRdTu.jpg

XML Settings:
https://pastebin.com/pvc4q7nU

Nothing specials. Just set ballad to x1, set setup ignore.

**Comment by Ivaar** [comment]
It appears to be resolved, good luck!

**Comment by ukkoclap** [comment]
Thanks a lot for your time updating this. Pianissomi now works again only its spamming pia + ballad again. What i've noticed it's used Pia as soon as Ballad comes off its cooldown.

**Comment by Ivaar** [comment]
Is your pianissimo target also on the ignore list?

**Comment by Ivaar** [comment]
Let me know if this fixes it.

**Comment by ukkoclap** [comment]
Piassimo works now. No loop anymore as well as Marches works. Thank you so much for updating your Bard addon!
