### ISSUE TITLE
Upgraded to new version and wont cast dummy songs

### ISSUE THREAD

**Issue by jmhgit** [Ivaar/Windower-addons#32]
Previous to this it was working perfectly with Terpander and Clarion.

I finished Duardabla, downloaded the newest version of singer and set up my gearswaps to accommodate for Duardabla and 4/5 songs. I now cannot get the dummy songs to trigger at all, I've tried setting dummy 1 and dummy 2 as paeons and minnes and my guy will just endlessly cycle through the set songs without playing the dummys. 

I'm stumped pls halp

**Comment by jmhgit** [comment]
I'm just guessing that it's not detecting my Duardabla? as no dummy songs are cast at all :/

//sing dummy [n] <song>  -  Set dummy songs, ignored if you do not own the proper equipment.**

**Comment by jmhgit** [comment]
Pretty stumped. I dont know what I did wrong but I played with it for like 2 hours, took a break, came back and reloaded it and it started playing the dummy songs.

**Comment by Ivaar** [comment]
Form a party with more than one player or call a trust, singing solo is broken. If you still have problems drop by my new support discord <https://discord.gg/3J38wkE>

**Comment by Ivaar** [comment]
Missed you most recent comments somehow. I'll look over the readme and make sure it reflects recent adjustments.
