### ISSUE TITLE
porter packer

### ISSUE THREAD

**Issue by Jneel34** [Ivaar/Windower-addons#38]
Export no longer works on FFXI porterpacker....evrytime i try i get  a run time error ending with "porterpacker.lua:324. attempy to index a field '?' (a nil value)

**Comment by johnarnfield** [comment]
See here for additional context: https://github.com/Windower/Lua/commit/191bc6fa1db5ef53dacb37a9ea0172b11bea99b0

Removing the reference to "0" in addons/libs/slips.lua:37 fixed the issue for me.

**Comment by Jneel34** [comment]
> See here for additional context: [Windower/Lua@191bc6f](https://github.com/Windower/Lua/commit/191bc6fa1db5ef53dacb37a9ea0172b11bea99b0)
> 
> Removing the "0" entry in addons/libs/slips.lua:37 fixed the issue for me.

sorry does that mean line 37?

**Comment by Jneel34** [comment]
Fixed Thanks John
