### ISSUE TITLE
CDC > CDC Burst properties not detected

### ISSUE THREAD

**Issue by xavikon** [Ivaar/Windower-addons#4]
When doing back to back CDC that results in light from a BLU, the lua does not return the burst properties.

**Comment by Ivaar** [comment]
Skillchains has been moved to its own repository https://github.com/Ivaar/Skillchains
Verify the burst properties display is enabled by typing "//sc ma on"
The second line will display the elements that will burst. Let me know if you still have problems.

**Comment by xavikon** [comment]
I created a fix, but have hacked around it since then to do other things.  I will isolate the changed I made from what is in the repo that were necessary for this specifically.  I had verified that //sc ma on was such that the burst elements displayed.  The problem only existed with CDC > CDC creating a level 4 light.  It would likely also occur in things like Fudo > Fudo which creates a lvl 4 light as well.  I think the problem had to do with the way the returned packet was interpreted.

**Comment by xavikon** [comment]
I compared what is up in the new repo vs what I have.  I've added a little auto-mb code for the purposes of simplifying multi-boxing, but the following I think is the major change:

Changing the end of display_results to the following, resolve the issue.  Basically, once the 2nd CDC landed, even with //sc ma on, the burst results/burst window disappeared, unlike a lvl3 light or lvl1 or 2 SCs.  I think this is due to it immediately removing the resonating status from the mob, since you can't go anywhere from an Umbra or a Radiance.

The below is a hack as opposed to a final fix.  I think the fix would be if the packet is light/darkness & no longer resonating then open a burst window with the light/darkness properties, but since no longer resonating, any new ws detected would result in a new window.

    if not resonating[targ].step then
        return ' Step: Closed >> [%s] >>':format(resonating[targ].ws.en)..burst..str
   elseif resonating[targ].step then
       return ' Step: %d >> [%s] >>':format(resonating[targ].step,resonating[targ].ws.en)..chain..burst..str
   end

**Comment by Ivaar** [comment]
I made a quick fix, I'll have to recode some things later.
